import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import UserProvider from "@/providers/UserProvider";
import { Toaster } from "react-hot-toast";
import Header from "@/app/Components/Header/Header";
import ContentProvider from "@/providers/ContentProvider";
import NextTopLoader from "nextjs-toploader";
import ModalProvider from "@/providers/ModalProvider";
import { GlobalProvider } from "@/context/globalContext";
import { SnippetsProvider } from "@/context/snippetsContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/7.0.0/css/all.min.css"
          integrity="sha512-DxV+EoADOkOygM4IR9yXP8Sb2qwgidEmeqAEmDKIOfPRQZOWbXCzLC6vjbZyy0vPisbH2SyW27+ddLVCN+OMzQ=="
          crossOrigin="anonymous"
          referrerPolicy="no-referrer"
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Toaster position="top-center" />
        <NextTopLoader showSpinner={false} color="#7263F3" height={2} />

        <UserProvider>
          <GlobalProvider>
            <SnippetsProvider>
              <ModalProvider />
              <div className="h-full">
                <Header />
                <ContentProvider>{children}</ContentProvider>
              </div>
            </SnippetsProvider>
          </GlobalProvider>
        </UserProvider>
      </body>
    </html>
  );
}
